spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:student
    username: AmnaS
    password: Aamna0907#
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

api:
  security:
    ignored: /api/v1/news,/api/v1/news/**