spring:
  boot:
    admin:
      client:
        url: http://localhost:8080/admin


  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: root
    password: aamna
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      open-in-view: false
    mysql:
      console:
        enabled: true

server:
  tomcat:
    connection-timeout: 300000

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1 hour in milliseconds
#
#logging:
#
#  level:
#    '[org.springframework.security]': DEBUG
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#
#



